version: "3.1"
services:
  apachephp:
    image: apachephp
    deploy:
     replicas: 1
#     restart_policy:
 #      condition: on-failure
     resources:
       limits:
         cpus: "0.1"
         memory: 50M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - C:\Users\Daniel\Desktop\Learning\DockerStuff\phpdev\www:/var/www/html
    networks:
      - webnet
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\Daniel\Desktop\Learning\DockerStuff\phpdev\db:/var/lib/mysql
    secrets:
      - mysql_db_root
    environment:
       #MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_db_root
       MYSQL_ROOT_PASSWORD: "password"
    networks:
      - webnet
  adminer:
    image: adminer
    ports:
        - 8080:8080
    networks:
      - webnet
secrets:
  mysql_db_root:
    external: true
networks:
  webnet: